spring.application.name=caampaign-analytics
spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=cipher
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true